[project]
name = "calorie-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.9",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
